
codecov:
  branch: master

coverage:
  precision: 2
  round: down
  range: "75...100"
  ignore:
    - docs/*
    - fastlane/*

  status:
    project:
      default:
        target: auto
        branches:
          - master

comment:
  layout: "header, diff, changes, sunburst, uncovered, tree"
  behavior: default
  branches:
    - master
