language: objective-c
# dist: osx
os: osx
osx_image: xcode8.3
xcode_sdk: iphonesimulator10.3

xcode_project: sapataz.xcodeproj

script:
  - xcodebuild -project toscoz.xcodeproj -scheme toscoz -configuration Debug -sdk iphonesimulator -destination "OS=10.3,name=iPhone 7" CODE_SIGNING_REQUIRED=NO clean build test analyze
  # - bundle exec danger

after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'toscoz'

notifications:
  email: false
  slack:
    rooms:
      - secure: tJZantT+f8uNPq3w0Y5UFezlpy1g6O5sHOnHi5x0K8yP6RPnQjStivHXvRCExzRJCIRvnv4k7Ha8ZULcc//JN2BcgnYIR0f4IF5N6OG20238MRS0IRjT+TPa2IWYfqyC7w4Qnea4tc4fhkOR9zVmr/EZfZ0M9srGC/vaxzDwmJb/f/1SZdaDvjjqKtl0KCT8cR/oFjT/+QPhTT6lH0m8AGdZjW6/4HhVVjzl3SJ/vfgdZe0mAFbgYT+AJpyjK5hvtgkjDjSu6K9q0Xn8mX28+WtxvzJuJQbOpupP2fXCZQMPGWuvHai7PWFq4NuFHd/af4fzMzwlVJBViXlPIxFNZas5OwqUBbRSgmbXf8xdBX9rY1T5skikfiIif0Yr+9AM2JD99r2b3J+LmAFIW80CAO4SvamF2rTdGUVogWdU7nRPIH3VaVUJGNVsmG39m05K8rVH2gJGw93+SOm5N05WP789kx8ZEilGFPRSkUmp/snNwpZZMZpN0lLq35tnkJ0YGiArevjqq3PPgugmSMPifu4D4ThNJcTLuhc81JCZzRIbdt+RkXTaDCMtOCaJIRLJMJqMUxsGs5TTfFUS2lWbObLjnNise9XHBuiRhu/+mxfhc4UipC+CusrYIZP/pFhFfDsNj8RU8PieuUbNoxzty/n1OdDeTqVEZmY6rmFAuc4=
    on_success: always
    on_failure: always
