# language
language: swift

# language options
osx_image: xcode11.3

# dependencies
addons:
  homebrew:
    packages:
    - swiftlint
    update: true

# cache
cache:
  - bundler

# branches to run

# global environment variables
env:
  global:
    - LANG=en_US.UTF-8

    - PROJECT="toscoz.xcodeproj"
    - IOS_SCHEME="toscoz"

    - IOS_SDK=iphonesimulator13.2

####################

jobs:
  include:
    - stage: resources
      name: "Swiftlint"
      script: swiftlint

    - &unit-test
      stage: unit tests
      name: "Unit Testing"
      env: SDK="$IOS_SDK" SCHEME="$IOS_SCHEME" DESTINATION="OS=13.2,name=iPhone 11 Pro"
      script: 
        - xcodebuild -version -sdk
        - xcodebuild analyze test -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -configuration Debug -destination "$DESTINATION" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO

    - <<: *unit-test
      env: SDK="$IOS_SDK" SCHEME="$IOS_SCHEME" DESTINATION="OS=13.2,name=iPhone 8"
      script:
        - xcodebuild -version -sdk
        - xcodebuild analyze test -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -configuration Debug -destination "$DESTINATION" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO
    - <<: *unit-test
      env: SDK="$IOS_SDK" SCHEME="$IOS_SCHEME" DESTINATION="OS=13.2,name=iPad Pro (11-inch)"
      script:
        - xcodebuild -version -sdk
        - xcodebuild analyze test -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -configuration Debug -destination "$DESTINATION" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO

stages:
- resources
- unit tests
#- ui tests