# language
language: swift

# language options
os: osx
osx_image: xcode11.3

# dependencies
addons:
  homebrew:
    packages:
    - swiftlint
    update: true

# cache
cache:
  - bundler

# branches to run

# global environment variables
env:
  global:
    - LANG=en_US.UTF-8

    - PROJECT="toscoz.xcodeproj"
    - IOS_SCHEME="toscoz"

    - IOS_SDK=iphonesimulator13.2

####################

jobs:
  include:
    - stage: resources
      name: "Swiftlint"
      script: swiftlint lint

    - &unit-test
      stage: unit tests
      name: "iPhone 11 Pro"
      env: SDK="$IOS_SDK" SCHEME="$IOS_SCHEME" DESTINATION="OS=13.3,name=iPhone 11 Pro"
      script: 
        - xcodebuild -version -sdk
        - xcodebuild clean test -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -configuration Debug -destination "$DESTINATION" -enableCodeCoverage YES ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO

    - <<: *unit-test
      name: "iPhone 8"
      env: SDK="$IOS_SDK" SCHEME="$IOS_SCHEME" DESTINATION="OS=13.3,name=iPhone 8"
      
    - <<: *unit-test
      name: "iPad Pro (11-inch)"
      env: SDK="$IOS_SDK" SCHEME="$IOS_SCHEME" DESTINATION="OS=13.3,name=iPad Pro (11-inch)"
      
    - stage: codeCoverage
      name: Codecov
      if: branch = master
      script: bash <(curl -s https://codecov.io/bash) -J 'toscoz'

stages:
- resources
- unit tests
#- ui tests
- codeCoverage