language: objective-c
# os: osx
osx_image: xcode8.3
xcode_sdk: iphonesimulator10.3

xcode_project: sapataz.xcodeproj

script:
- xcodebuild -project toscoz.xcodeproj -scheme toscoz -configuration Debug -sdk iphonesimulator -destination "OS=10.3.1,name=iPhone 7" CODE_SIGNING_REQUIRED=NO clean build test analyze

after_success:
- bash <(curl -s https://codecov.io/bash) -J 'toscoz'

notifications:
  email: false
  slack:
    rooms:
      secure: Au0K922OZijH3BHVMrasF4sYp6BCWtbRYyI60tnFx6SCjnDMmZfDjIFRwlrLqbe/GUcWludUICHUpwlztsErGJkvm4Xw3JLeqgNQE8pbwXku9kdDiqXLIZNdRT6GmnEEITChrwiRmHYtTS3wcQbapFk1rLWR+8leIn8ow3+zIWnla3aZ5UTWHgU+k1HZNFRcgpoH8y4uKKPQ3XPXrhwkEpbB3ywmiYZgUsPpvqMq7NeJASGHoqLxKiNkLqyKIeyvT+7boEM3smbg0mzc+uC0SFVP6BZ1rfAVjFag8pK01UVctQhfxtFgaM/KbipJcTvqoOwxxz4XRYfZBlFQeEElqtA63TiNMOlHcDdYUJABszUyxA1/3NjSN/WwczFRAN7bCFUYE/NDMMbbeptapdjfGRgBa7EsMFES2tUpicDO4cZNZg19Ymjut5BVTto2luov7FPKbefQJcOxynoS+e5+I8w4qoAlRgOdgyBBIP1BA2vDvs9ECvXp+6wJb++lVyTibrQozdhCN2Lk3dSo2gCJjc94zuHnsm1girhZuRQbJmaHorQ+y0DYCsNgpVrgugMbPai0C/RY7oBunvcrYskQXClqWMM1mB3g4z5ALTeK0rNlxkKEwH8G4idUjRN/3afWaAP9RpM3EQPon60msuhMsTufmXLafX5twTYki8OoB08=
    on_success: always
    on_failure: always
