author: "Jorge Moura"
author_url: http://www.jjorgemoura.com
copyright: Copyright © 2020 Jorge Moura
readme: README.md

github_url: https://github.com/jjorgemoura/toscoz
github_file_prefix: https://github.com/jjorgemoura/toscoz/tree/master

# root_url:
# docset_icon: fastlane/resources/docset-icon@2x.png

output: docs
theme: apple

sdk: iphoneos
# swift-version: 5.1
# source_directory: toscoz/
clean: true

hide_documentation_coverage: false
skip_undocumented: false
min_acl: internal

xcodebuild_arguments:
    - "-project"
    - "toscoz.xcodeproj"
    - "-scheme"
    - "toscoz"
