
# fastlane constants
fastlane_version "2.130.0"
default_platform :ios

## ios lanes setup ##
platform :ios do

  lane :check_resources do
    swiftlint
  end

  lane :run_unit_tests do
    scan(scheme: ENV["XCODE_SCHEME_TESTS"])
  end

  lane :run_ui_tests do
    scan(scheme: ENV["XCODE_SCHEME_UI_TESTS"])
  end

  lane :do_beta do |option|
    do_validation option
    #check_resources
    #run_unit_tests
    #run_ui_tests
    #bump_version option
    #set_tag
    #generate_documentation
    
    #gym(scheme: xcode_scheme_main, export_method: "development")
    # pilot(username: appleid_user, skip_submission: true)
  end


  ###### Auxiliar Lanes ######

  desc "Validate the version command and the branch. Must send parameter version=MAJOR, MINOR or PATCH"
  private_lane :do_validation do |option|

    #ensure_git_branch(
    #  branch: 'master'
    #)

    if option[:version]
      UI.important "Validating the version bump parameter with value: " + option[:version]
      if option[:version] != "MAJOR" && option[:version] != "MINOR" && option[:version] != "PATCH"
        UI.error "ATTENTION: Please, user the parameter 'version' with the values MAJOR, MINOR or PATCH!!!"
        UI.user_error! "Execution aborted by bad input!!!"
      end
    else
      UI.error "ATTENTION: Please, use the parameter 'version' to set the bump desired!!!"
      UI.user_error! "Execution aborted by bad input!!!"
    end
  end


end
