
# fastlane constants
fastlane_version "2.60.1"
default_platform :ios

# constants
TEAM_ID = "XXXXXX"
USERNAME = "XXXXXXX"

## ios lanes setup ##
platform :ios do

  # tests
  desc "Runs all the tests"
  lane :tests do
    test_unit
    test_ui
  end

  desc "Runs unit tests"
  lane :test_unit do |params|
    scan(scheme: "toscoz")
  end

  desc "Run UI tests"
  lane :test_ui do |params|
    scan(scheme: "toscozUITest")
  end


  # betas
  desc "Submit a new Beta Build to Apple TestFlight"
  lane :beta do
    # match(type: "development", readonly: true)
    gym(scheme: "toscoz", export_method: "development")
    pilot(
      username: "jjorge.moura@gmail.com",
      skip_submission: true
    )

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end


  # release
  desc "Deploy a new version to the App Store"
  lane :release do
    precheck
    # match(type: "appstore")
    # snapshot
    gym
    # deliver(force: true)
    # frameit
  end



  # constants
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    # carthage
  end

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end
