name: Beta

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Master Build
    runs-on: macOS-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Bundle Install 
      run: bundle update --bundler
    - name: Build and Tests 
      run: bundle exec fastlane run_unit_tests
